version: "3"

services:
  server:
    image: openjdk:8
    networks:
      - bridge
    container_name: server
  client:
    image: openjdk:8
    networks:
      - bridge
    container_name: client 
    volumes:
      - $PWD\client\result:/src/result 
networks:      
  bridge:
    driver: bridge
    external: true
    name: bridge